### ISSUE TITLE
请问如何保证内部微服务的安全

### ISSUE THREAD

**Issue by louchenaishang** [luoml/spring-cloud-example#1]
客户端直接访问rest或者通过网关访问都没有权限控制

是否可以在rest和zuul之间在加一个模块用来暴露对外接口以及接口内部调用内部微服务顺序并做权限控制

**Comment by luoml** [comment]
@louchenaishang，zuul用来做网关，对外接口统一走网关，内部微服务调用采用Feign等方式实现，在网关层进行安全控制等。
